### ISSUE TITLE
Error when adding ` inside tables

### ISSUE THREAD

**Issue by antonioreyna** [careteditor/caret#102]
The following error has occurred:

```
{
    "message": "Cannot read property 'start' of undefined",
    "version": "1.5.3",
    "platform": "darwin",
    "os": "15.6.0",
    "path": "web/Editor/Editor.js",
    "code": "this[_0xc65e[13]][_0xc65e[59]](_0x1f8ex2[_0xc65e[51]],_0x1f8ex2[_0xc65e[53]])},lineRange:function(_0x1f8ex2)",
    "line": 5,
    "column": 8512,
    "stack": [
        "at Object.getText (web/Editor/Editor.js:5:8512)",
        "at Object.<anonymous> (web/Editor/Editor.Markdown.Table.js:5:3540)",
        "at Array.forEach ((native)",
        "at Object._getTableData (web/Editor/Editor.Markdown.Table.js:5:3375)",
        "at Object._onInput (web/Editor/Editor.Markdown.Table.js:5:8435)",
        "at Object.trigger (web/Events.js:5:725)",
        "at Object.delete (web/Editor/Editor.Input.js:5:9273)",
        "at Object.char (web/Editor/Editor.Input.js:5:10282)",
        "at Object._onTextInput (web/Editor/Editor.Input.js:5:16097)"
    ]
}
```

**Comment by astoilkov** [comment]
Hi @antonioreyna,

I have tried to replicate the issue inside a table but without success. Can you provide a specific example where entering ` throws the error?

Thanks in advance.

**Comment by astoilkov** [comment]
I am closing this issue as we were unable to replicate the issue. It is also possible that we fixed it during other improvements and updates to the code since then.

However, if you are able to replicate it do not hesitate to write here so we could reopen the issue and investigate.

Thanks.
