### ISSUE TITLE
[BUG] Error when switching theme to Github. 

### ISSUE THREAD

**Issue by szainmehdi** [careteditor/caret#155]
I tried switching the theme to "Github" and an error occurred.

Version: Caret 1.8.0

The following error has occurred:
```
{
    "message": "Attempting to call a function in a renderer window that has been closed or released. Function provided here: MenuDesktop.js:5:1026.",
    "os": "OS X El Capitan",
    "stack": [
        "Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: MenuDesktop.js:5:1026.",
        "    at callIntoRenderer (/Applications/Caret.app/Contents/Resources/electron.asar/browser/rpc-server.js:192:19)",
        "    at MenuItem.click (/Applications/Caret.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)",
        "    at Function.executeCommand (/Applications/Caret.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)"
    ]
}
```

**Comment by astoilkov** [comment]
Can you consistently replicate the problem or it happened just once? I am asking because we can't seem to replicate it.

**Comment by szainmehdi** [comment]
The old "try turn it off and on again" seems to have done the trick. Not sure how it got in the broken state in the first place, but it's working fine now. Thanks.
