### ISSUE TITLE
Error when edit long file

### ISSUE THREAD

**Issue by ChangJoo-Park** [careteditor/caret#179]
The following error has occurred:
```
{
    "message": "Attempting to call a function in a renderer window that has been closed or released. Function provided here: Updates.js:5:4169.",
    "version": "1.9.3",
    "os": "macOS Sierra",
    "stack": [
        "Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Updates.js:5:4169.",
        "    at AutoUpdater.callIntoRenderer (/Applications/Caret.app/Contents/Resources/electron.asar/browser/rpc-server.js:192:19)",
        "    at emitOne (events.js:101:20)",
        "    at AutoUpdater.emit (events.js:188:7)"
    ]
}
```

**Comment by astoilkov** [comment]
Hi @ChangJoo-Park,

Do you know any steps for reproducing this issue? I am asking because we don't see any of our other users sending similar error reports and we don't seem to be able to replicate it.

Thanks in advance.
