### ISSUE TITLE
Cannot read property 'nodes' of undefined

### ISSUE THREAD

**Issue by cj** [careteditor/caret#187]
The following error has occurred:
```
{
    "message": "Cannot read property 'nodes' of undefined",
    "version": "1.11.2",
    "os": "macOS Sierra",
    "path": "web/Editor/Editor.Markdown.js",
    "code": "_0xdfbbxe=_0xdfbbx2[_0x41c4[102]][0],_0xdfbbxf=this[_0x41c4[0]][_0x41c4[108]](_0xdfbbxe),_0xdfbbx10=_0xdfbbxf[_0x41c4[110]](_0x41c4[109])",
    "line": 5,
    "column": 16186,
    "stack": [
        "at Object.setTaskChecked (web/Editor/Editor.Markdown.js:5:16186)",
        "at View._checkTaskList (packages/Preview/Preview.js:5:6580)"
    ]
}
```

**Comment by astoilkov** [comment]
Hi @cj,

Can you send us the text you were editing when this error occurred? I guess it happened when you clicked a checkbox in the preview.

Thanks for reporting. We really appreciate it.

**Comment by astoilkov** [comment]
I am closing this in favor of the more descriptive https://github.com/careteditor/caret/issues/218 issue.
