### ISSUE TITLE
Right click over text

### ISSUE THREAD

**Issue by tulu** [careteditor/caret#22]
The following error has occurred:
```
{
    "message": "Uncaught TypeError: Cannot read property 'top' of undefined",
    "line": 5,
    "column": 1294,
    "version": "0.4.4",
    "platform": "darwin",
    "os": "15.0.0",
    "path": "/Applications/Caret.app/Contents/Resources/app.asar/web/Editor.Menu.js",
    "stack": [
        "at Object.EditorMenu._showing (/Applications/Caret.app/Contents/Resources/app.asar/web/Editor.Menu.js:5:1294)",
        "at loopEvents (/Applications/Caret.app/Contents/Resources/app.asar/web/Events.js:5:229)",
        "at List.Events.trigger (/Applications/Caret.app/Contents/Resources/app.asar/web/Events.js:5:527)",
        "at List.inherit.show (/Applications/Caret.app/Contents/Resources/app.asar/web/ContextMenu.js:5:435)",
        "at Object.EditorMenu.show (/Applications/Caret.app/Contents/Resources/app.asar/web/Editor.Menu.js:5:657)",
        "at HTMLDocument.<anonymous> (/Applications/Caret.app/Contents/Resources/app.asar/packages/Editor/EditorDesktop.js:5:1641)"
    ]
}
```

**Comment by astoilkov** [comment]
Fixed.

You should get an in-app update notification some time next week.

Thanks a lot for reporting this :)
