### ISSUE TITLE
An error happened during the trial version. 

### ISSUE THREAD

**Issue by rafaell-lycan** [careteditor/caret#228]
The following error has occurred:
```
{
    "message": "Could not call remote function ''. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from null\nError: Could not call remote function ''. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from null\n    at callFunction (C:\\Users\\RLAM\\AppData\\Local\\Caret\\app-1.13.1\\resources\\electron.asar\\browser\\rpc-server.js:235:11)\n    at EventEmitter.<anonymous> (C:\\Users\\RLAM\\AppData\\Local\\Caret\\app-1.13.1\\resources\\electron.asar\\browser\\rpc-server.js:342:5)\n    at emitMany (events.js:127:13)\n    at EventEmitter.emit (events.js:201:7)\n    at WebContents.<anonymous> (C:\\Users\\RLAM\\AppData\\Local\\Caret\\app-1.13.1\\resources\\electron.asar\\browser\\api\\web-contents.js:231:13)\n    at emitTwo (events.js:106:13)\n    at WebContents.emit (events.js:191:7)",
    "version": "1.13.1",
    "os": "Windows 8.1",
    "path": "C:\\Users\\RLAM\\AppData\\Local\\Caret\\app-1.13.1\\resources\\electron.asar\\renderer\\api\\remote.js",
    "code": "throw new Error(meta.message + '\\n' + meta.stack)",
    "line": 217,
    "column": 7,
    "stack": [
        "Error: Could not call remote function ''. Check that the function

**Comment by astoilkov** [comment]
Hi @rafaell-lycan,

Do you have any replication steps? Is this happened once or multiple times?

Thanks in advance.

**Comment by rafaell-lycan** [comment]
Hey, I just updated to the last version and so far so good.

The problem was when start Caret and it loads the previous file.

I'll keep you updated about any further issues.

Best

**Comment by astoilkov** [comment]
Closing the issue for now. Please feel free to write here if the problem appears again.
