### ISSUE TITLE
PDF export failed

### ISSUE THREAD

**Issue by bearhagen** [careteditor/caret#243]
The following error has occurred:
```
{
    "message": "Could not call remote function ''. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from null\nError: Could not call remote function ''. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from null\n    at callFunction (C:\\Users\\bjorn\\AppData\\Local\\Caret\\app-1.14.2\\resources\\electron.asar\\browser\\rpc-server.js:258:11)\n    at EventEmitter.<anonymous> (C:\\Users\\bjorn\\AppData\\Local\\Caret\\app-1.14.2\\resources\\electron.asar\\browser\\rpc-server.js:365:5)\n    at emitMany (events.js:127:13)\n    at EventEmitter.emit (events.js:201:7)\n    at WebContents.<anonymous> (C:\\Users\\bjorn\\AppData\\Local\\Caret\\app-1.14.2\\resources\\electron.asar\\browser\\api\\web-contents.js:234:37)\n    at emitTwo (events.js:106:13)\n    at WebContents.emit (events.js:191:7)",
    "version": "1.14.2",
    "os": "Windows 10",
    "path": "C:\\Users\\bjorn\\AppData\\Local\\Caret\\app-1.14.2\\resources\\electron.asar\\renderer\\api\\remote.js",
    "code": "throw new Error(meta.message + '\\n' + meta.stack)",
    "line": 217,
    "column": 7,
    "stack": [
        "Error: Could not call remote function ''. Check that the funct

**Comment by astoilkov** [comment]
Hi @bearhagen,

Can you reproduce the error consistently or it was one time thing? If yes can you share the steps of reproducing the problem.

Thanks in advance.

**Comment by bearhagen** [comment]
It seems like a one time thing. Didn't do anything special. I was just trying to export what I had written to PDF.
