### ISSUE TITLE
Cannot read property 'nodes' of undefined

### ISSUE THREAD

**Issue by darve** [careteditor/caret#272]
The following error has occurred:
```
{
    "message": "Cannot read property 'nodes' of undefined",
    "version": "2.0.5",
    "os": "macOS Sierra",
    "path": "web/Editor/Editor.Markdown.js",
    "code": "_0xffd0x13=t[_0x3c88[132]][0],_0xffd0x14=this[_0x3c88[50]][_0x3c88[168]](_0xffd0x13),_0xffd0x15=_0xffd0x14[_0x3c88[170]](_0x3c88[169])",
    "line": 5,
    "column": 23715,
    "stack": [
        "at _0xffd0x3.value (web/Editor/Editor.Markdown.js:5:23715)",
        "at t.value (packages/Preview/Preview.js:5:8692)"
    ]
}
```

**Comment by astoilkov** [comment]
Did this happen when you clicked a checkbox in the preview?

**Comment by darve** [comment]
Yes indeed! I created several checkboxes, pressed CMD + SHIFT + R to switch to preview mode, and it after checking some of them it happened.

Interestingly when I switched back it had the wrong checkboxes marked.

**Comment by astoilkov** [comment]
Is it possible that you send the text that caused the problem so we could investigate why this error has occurred?

**Comment by darve** [comment]
Sure thing:

- [x] header
- [x] cookieNotification
- [x] account 
- [x] footer
- [x] notification
- [x] history
- [x] currentPass
- [x] allowance
- [x] topup
- [x] waitingPasses
- [ ] getAnAddon
- [ ] FAQ
- [ ] terms

**Comment by darve** [comment]
Try ticking `getAnAddon`

**Comment by astoilkov** [comment]
Hmm. I can't replicate the issue. I tried copying the text opening the preview and clicking on the `genAnAddon` checkbox and everything worked fine. Do you have anything in mind that I can be missing?

**Comment by darve** [comment]
Now it's doing this...

![issue](https://cloud.githubusercontent.com/assets/1042366/24452468/53fdf9dc-147b-11e7-88d7-a5a9f75100f6.gif)

**Comment by astoilkov** [comment]
We have known this bug for a long time as others have reported it. For now we haven't been able to reproduce it successfully. If you have any idea on how we could replicate it on our side this would be greatly appreciated. The best thing would be steps to reproduce.

Thanks in advance.
