### ISSUE TITLE
Format->Math Mode fails if nothing highlighted and cursor in expression

### ISSUE THREAD

**Issue by jcdunagan** [careteditor/caret#315]
To replicate:
1. type a latex expression (e.g. "$$x$$")
2. place cursor within body of expression.
3. Select Format->Math.

The following error has occurred:
```
{
    "message": "Cannot read property 'start' of undefined",
    "version": "2.0.11",
    "os": "macOS Sierra",
    "path": "web/Editor/Editor.Markdown.Format.js",
    "code": "i=this._editor,n=e.nodes[1].start-e.start,o=t.caret-t.start",
    "line": 5,
    "column": 4892,
    "stack": [
        "at t.value (web/Editor/Editor.Markdown.Format.js:5:4892)",
        "at /private/var/folders/82/h23wrhm13cz1cxshv81zrbwr0000gn/T/AppTranslocation/E5C15BFE-798F-41DC-9B71-8781B8C527C2/d/Caret.app/Contents/Resources/app.asar/web/Editor/Editor.Markdown.Format.js:5:4773",
        "at t.value (web/Editor/Editor.Selection.js:5:1304)",
        "at _0x6982x3.value (web/Editor/Editor.js:5:13062)",
        "at t.value (web/Editor/Editor.Markdown.Format.js:5:4672)",
        "at t.value (web/Editor/Editor.Markdown.Format.js:5:945)",
        "at t.value (web/Extension.Command.js:5:2337)",
        "at _0xb0ecx3.value (CaretDesktop.js:5:20346)",
        "at emitThree ((events.js:116:13)",
        "at EventEmitter.emit ((events.js:194:7)"
    ]
}
```

**Comment by astoilkov** [comment]
We have resolved this issue internally. We will release a version that includes the fix in the next 3-4 days and notify you when this happens.

Thanks for reporting.

**Comment by astoilkov** [comment]
This is now fixed in the latest version of Caret. Closing this issue.
