### ISSUE TITLE
Error I ran into while in the Keyboard shortcuts page

### ISSUE THREAD

**Issue by DougBeney** [careteditor/caret#387]
I was in the keyboard shortcuts editor and noticed the Cmd+T shortcut, which I didn't previously know about. I tried to hit enter to go back a directory (like this: http://imgur.com/a/T9Dlu) and ran into this error. 

The following error has occurred:
```
{
    "message": "Cannot read property 'text' of undefined",
    "version": "2.1.3",
    "os": "macOS Sierra",
    "path": "packages/Navigator/Navigator.js",
    "code": ").join(\"\"),filterText:r[r.length-1].text,className:n.join(\" \"),isMarkdown:this._mdFormats.indexOf(path.ext(e))!=-1}}.bind(this)).filter(function(t)",
    "line": 5,
    "column": 3036,
    "stack": [
        "at e.<anonymous> (packages/Navigator/Navigator.js:5:3036)",
        "at Array.map ((native)",
        "at e.value (packages/Navigator/Navigator.js:5:2384)",
        "at e.value (packages/Navigator/Navigator.js:5:1926)",
        "at e.value (packages/Navigator/Navigator.js:5:1974)",
        "at e.value (packages/Navigator/Navigator.js:5:4789)",
        "at t.value (web/Events.js:5:1330)",
        "at t.value (web/List.js:5:2681)",
        "at t.value (web/Extension.Command.js:5:2337)",
        "at t.value (web/Extension.Command.js:5:2554)"
    ]
}
```

**Comment by astoilkov** [comment]
I am closing this issue as it was fixed a while ago.

Thanks for reporting.
