### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by kevindoveton** [careteditor/caret#389]
error happened after hitting command + f to search, search text was already in search box from previous search 

The following error has occurred:
```
{
    "message": "Cannot read property 'type' of undefined",
    "version": "2.1.3",
    "os": "macOS Sierra",
    "path": "web/Editor/Editor.Tree.js",
    "code": "",
    "line": 5,
    "column": 3496,
    "stack": [
        "at e.value (web/Editor/Editor.Tree.js:5:3496)",
        "at t.value (web/Editor/Editor.Find.js:5:4006)",
        "at _0xf283x2.value (web/Editor/TilesHighlighter.js:5:7967)",
        "at /Applications/Caret.app/Contents/Resources/app.asar/web/Editor/TilesHighlighter.js:5:7448",
        "at Array.forEach ((native)",
        "at _0xf283x2.value (web/Editor/TilesHighlighter.js:5:7406)",
        "at _0xf283x2.value (web/Editor/TilesHighlighter.js:5:6994)",
        "at _0xf283x2.<anonymous> (web/Editor/TilesHighlighter.js:5:5041)",
        "at Array.forEach ((native)",
        "at _0xf283x2.value (web/Editor/TilesHighlighter.js:5:4960)",
        "at _0xf283x2.value (web/Editor/TilesHighlighter.js:5:4335)"
    ]
}
```

**Comment by astoilkov** [comment]
Closing this issue as this was fixed a while ago.

Thanks for reporting.
