### ISSUE TITLE
When opening a file with File Navigator.

### ISSUE THREAD

**Issue by pslobo** [careteditor/caret#401]
Just downloaded Version 3 and tried to open an existing file using <kbd>Cmd</kbd> + <kbd>T</kbd>

The following error has occurred:
```
{
    "message": "this[_0x47aa[94]][_0x47aa[93]] is not a function",
    "version": "3.0.0",
    "os": "macOS Sierra",
    "path": "CaretDesktop.js",
    "code": "this[_0x47aa[94]][_0x47aa[93]](e)?this[_0x47aa[94]][_0x47aa[89]](e):require(_0x47aa[89])(e,_0x47aa[95]== process[_0x47aa[39]]?_0x47aa[96]:null)}},",
    "line": 5,
    "column": 18814,
    "stack": [
        "at _0xcaa6x3.value (CaretDesktop.js:5:18814)",
        "at e.value (packages/Navigator/Navigator.js:5:2917)",
        "at t.value (web/Events.js:5:1335)",
        "at t.value (web/List.js:5:2285)",
        "at t.value (web/Extension.Command.js:5:2411)",
        "at t.value (web/Extension.Command.js:5:2628)"
    ]
}
```

**Comment by astoilkov** [comment]
We have released 3.0 now officially where this issue is fixed. You could download and install 3.0 again and the issue will be fixed.

Thanks for reporting. Closing this issue.
