### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by m1guelpf** [careteditor/caret#447]
The following error has occurred:
```
{
    "message": "Cannot read property 'includes' of undefined",
    "version": "3.2.3",
    "os": "Linux 4.8",
    "path": "web/Editor/Editor.Input.js",
    "code": "throw _0x8b51x9}}}}}",
    "line": 5,
    "column": 22449,
    "stack": [
        "at _0x8962x3.value (web/Editor/Editor.Markdown.js:5:27256)",
        "at _0x8962x3.value (web/Editor/Editor.Markdown.js:5:38891)",
        "at t.value (web/Events.js:5:1330)",
        "at _0x8b51x2.<anonymous> (web/Editor/Editor.Input.js:5:12697)",
        "at t.value (web/Editor/Editor.Selection.js:5:1304)",
        "at t.value (web/Editor/Editor.js:5:14478)",
        "at _0x8b51x2.value (web/Editor/Editor.Input.js:5:12580)",
        "at _0x8b51x2.value (web/Editor/Editor.Input.js:5:22283)"
    ]
}
```

**Comment by astoilkov** [comment]
Do you know how it can be reproduced?

**Comment by m1guelpf** [comment]
@astoilkov I don't know if it's related, but I was installing virtualbox, and suddently all the system hanged, then Caret & other electron apps were closed.
