### ISSUE TITLE
  The following error has occurred:

### ISSUE THREAD

**Issue by jw447** [careteditor/caret#505]
The following error has occurred:
```
{
    "message": "Error processing argument at index 0, conversion failure from null",
    "version": "3.4.3",
    "os": "macOS Sierra",
    "stack": [
        "TypeError: Error processing argument at index 0, conversion failure from null",
        "    at Menu.popup (/Applications/Caret.app/Contents/Resources/electron.asar/browser/api/menu.js:180:8)",
        "    at EventEmitter.<anonymous> (/Applications/Caret.app/Contents/Resources/app.asar/extensions/Menu/menu--main.js:5:1602)",
        "    at emitTwo (events.js:106:13)",
        "    at EventEmitter.emit (events.js:194:7)",
        "    at WebContents.<anonymous> (/Applications/Caret.app/Contents/Resources/electron.asar/browser/api/web-contents.js:247:13)",
        "    at emitTwo (events.js:106:13)",
        "    at WebContents.emit (events.js:194:7)"
    ]
}
```

**Comment by astoilkov** [comment]
I am closing this issue in favor of https://github.com/careteditor/caret/issues/391 which describes the same issue.
