### ISSUE TITLE
Error after task list state change in preview

### ISSUE THREAD

**Issue by enovid** [careteditor/caret#553]
This error occurs after changing the state of a task list checkbox in preview mode and then switching back to editor mode.

The following error has occurred:
```
{
    "message": "Cannot read property 'nodes' of undefined",
    "version": "3.4.6",
    "os": "macOS High Sierra",
    "path": "web/Editor/Editor.Markdown.js",
    "code": "_0xa799x4=t[_0x6864[149]][0],_0xa799x16=this[_0x6864[56]][_0x6864[88]](_0xa799x4),_0xa799x17=_0xa799x16[_0x6864[184]](_0x6864[183])",
    "line": 5,
    "column": 26369,
    "stack": [
        "at _0xa799x3.value (web/Editor/Editor.Markdown.js:5:26369)",
        "at Preview._checkTaskList (extensions/Preview/Preview.js:399:27)"
    ]
}
```

**Comment by astoilkov** [comment]
Hi @enovid,

Thanks for reporting this issue. Do you have steps for reproducing this issue?

Thanks in advance.
