### ISSUE TITLE
Caret 4 Beta - Path must be a string. Received undefined

### ISSUE THREAD

**Issue by SteveEdson** [careteditor/caret#590]
Getting this issue when going to View -> Preview, and then pressing escape.

The following error has occurred:
```
{
    "message": "Path must be a string. Received undefined",
    "version": "4.0.0-beta0",
    "os": "macOS High Sierra",
    "path": "path.js",
    "line": 7,
    "column": 5,
    "stack": [
        "at assertPath ((path.js:7:11)",
        "at Object.basename ((path.js:1355:5)",
        "at PathWrap._update (extensions/Path/PathWrap.js:5:584)",
        "at EditorDesktop.trigger (node_modules/desktop/Events.js:76:27)",
        "at EditorDesktop._resize (extensions/Editor/Editor/Editor.js:5:5319)"
    ]
}
```

**Comment by astoilkov** [comment]
This is now fixed in a new Caret 4.0 Beta release. You can download it [here](https://caret.io/4beta/).

Closing this issue. Thanks so much for trying out the Beta release!
