### ISSUE TITLE
When invoking the command palette, things sometimes go badly

### ISSUE THREAD

**Issue by chriskrycho** [careteditor/caret#622]
To reproduce: I couldn't say, unfortunately. At unpredictable intervals, hitting <kbd>⌘</kbd><kbd>⇧</kbd><kbd>P</kbd> will fail to launch the command palette, and pop up the "Error has occurred" message (which is how I ended up here).

The following error has occurred:
```
{
    "message": "Cannot read property 'type' of undefined",
    "version": "4.0.0-beta6",
    "os": "macOS High Sierra",
    "path": "extensions/Commands/Commands.js",
    "code": "\"checkbox\"==e.type",
    "line": 5,
    "column": 961,
    "stack": [
        "at Commands._createItem (extensions/Commands/Commands.js:5:961)",
        "at e.length.s.unshift.e.map.e (extensions/Commands/Commands.js:5:735)",
        "at Array.map ((native)",
        "at Commands.update (extensions/Commands/Commands.js:5:688)",
        "at Object.PopupFilterView.on [as callback] (node_modules/desktop/PopupFilterView.js:19:32)",
        "at Commands.trigger (node_modules/desktop/Events.js:76:27)",
        "at Commands.show (node_modules/desktop/View.js:25:10)",
        "at Commands.toggle (node_modules/desktop/View.js:44:12)",
        "at ExtensionCommand.exec (node_modules/desktop/Extension.Command.js:83:17)",
        "at ExtensionCommand._onKeyDown (node_modules/desktop/Extension.Command.js:98:14)"
    ]
}
```

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 4.0 Beta release.

Closing this issue. Thanks for reporting.
