### ISSUE TITLE
Image import Error

### ISSUE THREAD

**Issue by boraJeon** [careteditor/caret#642]
The following error has occurred:
```
{
    "message": "Error processing argument at index 0, conversion failure from null",
    "version": "3.4.6",
    "os": "macOS High Sierra",
    "stack": [
        "TypeError: Error processing argument at index 0, conversion failure from null",
        "    at Menu.popup (/Applications/Caret.app/Contents/Resources/electron.asar/browser/api/menu.js:180:8)",
        "    at EventEmitter.<anonymous> (/Applications/Caret.app/Contents/Resources/app.asar/extensions/Menu/menu--main.js:5:1602)",
        "    at emitTwo (events.js:106:13)",
        "    at EventEmitter.emit (events.js:194:7)",
        "    at WebContents.<anonymous> (/Applications/Caret.app/Contents/Resources/electron.asar/browser/api/web-contents.js:247:13)",
        "    at emitTwo (events.js:106:13)",
        "    at WebContents.emit (events.js:194:7)"
    ]
}
```

**Comment by astoilkov** [comment]
This is fixed in the latest Caret 4.0 Beta release. You could download it from [our site](https://caret.io) or wait for the update in the official channel.

Closing this issue. Thanks for reporting.
