### ISSUE TITLE
First error "Cannot read property 'filePath' of undefined"

### ISSUE THREAD

**Issue by putsan** [careteditor/caret#660]
The following error has occurred:
```
{
    "message": "Cannot read property 'filePath' of undefined",
    "version": "4.0.0-beta8",
    "os": "Linux 4.13",
    "path": "extensions/Tabs/Tabs.js",
    "code": "e=this._list.selectedItem().filePath,t=[",
    "line": 5,
    "column": 4624,
    "stack": [
        "at Tabs._onContextMenu (extensions/Tabs/Tabs.js:5:4624)",
        "at Menu._onContextMenu (extensions/Menu/Menu.js:5:1807)"
    ]
}
```

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret Beta update.

Closing this issue. Thanks for reporting.
