### ISSUE TITLE
V4 Beta 9: Cannot find module 'emojis'

### ISSUE THREAD

**Issue by klanchman** [careteditor/caret#666]
Files that contain emoji fail to load with the following error:

The following error has occurred:
```
{
    "message": "Cannot find module 'emojis'",
    "version": "4.0.0-beta9",
    "os": "macOS High Sierra",
    "path": "module.js",
    "line": 472,
    "column": 5,
    "stack": [
        "at Module._resolveFilename ((module.js:470:15)",
        "at Function.Module._resolveFilename ((/Applications/Caret Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)",
        "at Module.require (index.js:13:37)",
        "at require ((internal/module.js:20:19)",
        "at Slicedown.module.exports.parse [as inline-emoji] (node_modules/markdown/extensions/inline-emoji.js:13:17)",
        "at Slicedown.line (node_modules/markdown/Slicedown.js:883:46)",
        "at Slicedown._parseInlines (node_modules/markdown/Slicedown.js:267:32)",
        "at Slicedown._parseInlines (node_modules/markdown/Slicedown.js:270:32)",
        "at Slicedown._lines (node_modules/markdown/Slicedown.js:245:19)",
        "at Slicedown._parseInlines (node_modules/markdown/Slicedown.js:263:32)",
        "at Slicedown._parseInlines (node_modules/markdown/Slicedown.js:270:32)",
        "at Slicedown._lines (node_modules/markdown/Slicedown.js:245:19)",
        "at Slicedown._parseInlines (node_modules/markdown/Slicedown.js:263:32)",
        "at Slicedown._parseInlines (node_modules/markdown/Slicedown.js:270:32)",
        "at Slicedown._lines (node_modules/markdown/Slicedown.js:245:19)",
        "at Slicedown._parseInlines (node_modules/markdown/Slicedown.js:263:32)",
        "at Slicedown._parseInlines (node_modules/markdown/Slicedown.js:270:32)",
        "at Slicedown._lines (node_modules/markdown/Slicedown.js:245:19)",
        "at Slicedown._parseInlines (node_modules/markdown/Slicedown.js:263:32)",
        "at Slicedown._parseInlines (node_modules/markdown/Slicedown.js:270:32)"
    ],
    "count": 3
}
```

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret Beta update.

Closing this issue. Thanks for reporting.
