### ISSUE TITLE
Cannot find module 'emojis' - 4.0.0-beta9

### ISSUE THREAD

**Issue by codemonkee** [careteditor/caret#669]
Right clicks on Leaf Blocks and selected convert to text, produced the following error.
Closing Caret and re-opening, the UI seems to be broken when using the mouse, the file list, editor, preview and menu sections do not respond to the mouse.

Pressing Alt on the keyboard will open the menu and able to close the file, reopening caret and the `Markdown Support.md` file, the UI is usable, but still presents the "error has occurred.

The following error has occurred:
```
{
    "message": "Cannot find module 'emojis'",
    "version": "4.0.0-beta9",
    "os": "Windows 10",
    "path": "module.js",
    "line": 472,
    "column": 5,
    "stack": [
        "at Module._resolveFilename ((module.js:470:15)",
        "at Function.Module._resolveFilename ((C:\\Users\\twhitehead\\AppData\\Local\\caret-beta\\app-4.0.0-beta9\\resources\\electron.asar\\common\\reset-search-paths.js:35:12)",
        "at Module.require (index.js:13:37)",
        "at require ((internal/module.js:20:19)",
        "at Slicedown.module.exports.parse [as inline-emoji] (node_modules\\markdown\\extensions\\inline-emoji.js:13:17)",
        "at Slicedown.line (node_modules\\markdown\\Slicedown.js:883:46)",
        "at Slicedown._parseInlines (node_modules\\markdown\\Slicedown.js:267:32)",
        "at Slicedown._parseInlines (node_modules\\markdown\\Slicedown.js:270:32)",
        "at Slicedown._lines (node_modules\\markdown\\Slicedown.js:245:19)",
        "at Slicedown.parse (node_modules\\markdown\\Slicedown.js:110:23)",
        "at Markdown.parse (node_modules\\markdown\\index.js:19:27)",
        "at EditorMarkdownTree._parse (extensions\\Editor\\Editor\\Editor.Markdown.Tree.js:5:3990)",
        "at EditorMarkdownTree._onTextChange (extensions\\Edi

**Comment by codemonkee** [comment]
possible duplicate of #666

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret Beta update.

Closing this issue. Thanks for reporting.
