### ISSUE TITLE
Error "Cannot read property '0' of null" when editing quote block - 4.0.0-beta9

### ISSUE THREAD

**Issue by codemonkee** [careteditor/caret#671]
While editing a quote block with a code block inside.

```
>jibberjabber
> ~~~
> blah
> ~~~
>
```

I was editing the file and placed a new line after a `>` and before the first `~~~` to be the following markdown with the intent to expand it.

```
>jibberjabber
> 
> ~~~
> blah
> ~~~
>
```

The following error has occurred:
```
{
    "message": "Cannot read property '0' of null",
    "version": "4.0.0-beta9",
    "os": "Windows 10",
    "path": "extensions\\Editor\\Editor\\Editor.Markdown.Assist.js",
    "code": "RegExp(\"\\\\\"+i.marker+\"+\"))[0].length,s=this._editor.text.indent(e)+\"\\n\"+this._editor.text.indent(i.start)+i.marker.repeat(n)",
    "line": 5,
    "column": 3372,
    "stack": [
        "at EditorDesktop.i.nodes.length._editor.lineRange.start.e._editor.once (extensions\\Editor\\Editor\\Editor.Markdown.Assist.js:5:3372)",
        "at Object.wrapper [as callback] (node_modules\\desktop\\Events.js:23:23)",
        "at EditorDesktop.trigger (node_modules\\desktop\\Events.js:76:27)",
        "at EditorInput.<anonymous> (extensions\\Editor\\Editor\\Editor.Input.js:5:3292)",
        "at EditorSelection.each (extensions\\Editor\\Editor\\Editor.Selection.js:5:906)",
        "at EditorDesktop.getSelections (extensions\\Editor\\Editor\\Editor.js:5:2444)",
        "at EditorInput.char (extensions\\Editor\\Editor\\Editor.Input.js:5:2946)",
        "at EditorInput._onTextInput (extensions\\Editor\\Editor\\Editor.Input.js:5:9117)"
    ],
    "count": 6
}
```

**Comment by astoilkov** [comment]
Hi @codemonkee,

I have tried to replicate the issue but without success. Does the issue successfully replicates consistently in a document containing only the provided text?

Thanks in advance.

**Comment by codemonkee** [comment]
Hi @astoilkov - I tried to replicate the issue again when I got in today. using a with a new file and the existing file, I was unable to reproduce the error.

I'll keep an eye out and re-open the issue if I see it again and try and provide more details around it.
