### ISSUE TITLE
open a folder then click "save"

### ISSUE THREAD

**Issue by talkingtab** [careteditor/caret#677]
Reproduce By
1. Start caret
2. Open a folder
3. Click "save"

The following error has occurred:
```
{
    "message": "Path must be a string. Received null",
    "version": "4.0.0-beta9",
    "os": "macOS High Sierra",
    "path": "path.js",
    "line": 7,
    "column": 5,
    "stack": [
        "at assertPath ((path.js:7:11)",
        "at Object.extname ((path.js:1431:5)",
        "at File.saveDialog (extensions/File/File.js:5:4764)",
        "at File.saveAs (extensions/File/File.js:5:3555)",
        "at ExtensionCommand.exec (node_modules/desktop/Extension.Command.js:83:17)",
        "at Caret.execCommand (Caret.js:5:1575)",
        "at EventEmitter.electron.ipcRenderer.on (Caret.js:5:6897)",
        "at emitThree ((events.js:116:13)",
        "at EventEmitter.emit ((events.js:197:7)"
    ],
    "count": 1
}
```

**Comment by astoilkov** [comment]
Hi,

Thanks for reporting this bug. We will investigate it and fix it.
