### ISSUE TITLE
Cannot find module 'emojis'

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#678]
Happened to me when I was switching files in the sidebar.

```
{
    "message": "Cannot find module 'emojis'",
    "version": "4.0.0-beta9",
    "os": "Windows 10",
    "path": "module.js",
    "line": 472,
    "column": 5,
    "stack": [
        "at Module._resolveFilename ((module.js:470:15)",
        "at Function.Module._resolveFilename ((C:\\Users\\borek\\AppData\\Local\\caret-beta\\app-4.0.0-beta9\\resources\\electron.asar\\common\\reset-search-paths.js:35:12)",
        "at Module.require (index.js:13:37)",
        "at require ((internal/module.js:20:19)",
        "at Slicedown.module.exports.parse [as inline-emoji] (node_modules\\markdown\\extensions\\inline-emoji.js:13:17)",
        "at Slicedown.line (node_modules\\markdown\\Slicedown.js:883:46)",
        "at Slicedown._parseInlines (node_modules\\markdown\\Slicedown.js:267:32)",
        "at Slicedown._parseInlines (node_modules\\markdown\\Slicedown.js:270:32)",
        "at Slicedown._parseInlines (node_modules\\markdown\\Slicedown.js:270:32)",
        "at Slicedown._parseInlines (node_modules\\markdown\\Slicedown.js:270:32)",
        "at Slicedown._parseInlines (node_modules\\markdown\\Slicedown.js:270:32)",
        "at Slicedown._parseInlines (node_modules\\markdown\\Slicedown.js:270:32)",
        "at Slicedown._lines (node_modules\\markdown\\Slicedown.js:245:19)",
        "at Slicedown.parse (node_modules\\markdown\\Slicedown.js:110:23)",
        "at Markdown.parse (node_modules\\markdown\\index.js:19:27)",
        "at EditorMarkdownTree._parse (extensions\\Editor\\Editor\\Editor.Markdown.Tree.js:5:3990)",
        "at EditorMarkdownTree._onTextChange (extensions\\Editor\\Editor\\Editor.Markdown.Tree.js:5:2435)",
        "at EditorDesktop.trigger (node_modules\\desktop\\Events.js:76:27)",
        "at s.forEach.t (extensions\\Editor\\Editor\\Editor.js:5:6184)",
        "at Array.forEach ((native)"
    ],
    "count": 1
}
```

**Comment by astoilkov** [comment]
This will be fixed in the next beta release. Thanks for reporting.

**Comment by astoilkov** [comment]
This is now fixed in the newly release Caret Beta update.

Closing this issue. Thanks for reporting.
