### ISSUE TITLE
Cannot open files

### ISSUE THREAD

**Issue by illright** [careteditor/caret#713]
The following error has occurred:
```
{
    "message": "this.open is not a function",
    "version": "4.0.0-rc3",
    "os": "Linux 4.16",
    "path": "extensions/File/File.js",
    "code": "(\"dir\"==caret.fs.type(e[0])?caret.project.open(e[0]):this.open(e[0]),!0)}saveDialog(t)",
    "line": 5,
    "column": 1911,
    "count": 2,
    "stack": [
        "at File.openDialog (extensions/File/File.js:5:1911)",
        "at ExtensionCommand.exec (node_modules/desktop/Extension.Command.js:83:17)",
        "at Caret.execCommand (Caret.js:5:1575)",
        "at EventEmitter.electron.ipcRenderer.on (Caret.js:5:6980)",
        "at emitThree ((events.js:116:13)",
        "at EventEmitter.emit ((events.js:197:7)"
    ]
}
```

Seen on Ubuntu 17.10.1

**Comment by astoilkov** [comment]
This bug has been fixed in the latest Caret Beta RC4 update.

Closing this issue. Thanks for reporting.
