### ISSUE TITLE
Error on ctrl-R to new folder

### ISSUE THREAD

**Issue by richardxu100** [careteditor/caret#714]
The following error has occurred:
```
{
    "message": "Path must be a string. Received undefined",
    "version": "4.0.0-rc4",
    "os": "macOS High Sierra",
    "path": "path.js",
    "line": 7,
    "column": 5,
    "count": 1,
    "stack": [
        "at assertPath ((path.js:7:11)",
        "at Object.dirname ((path.js:1324:5)",
        "at Path.sliceFile (extensions/Path/Path.js:5:1195)",
        "at e._tabs.map (extensions/Tabs/Tabs.js:5:2773)",
        "at Array.map ((native)",
        "at Tabs._update (extensions/Tabs/Tabs.js:5:2744)",
        "at Tabs._onTabSave (extensions/Tabs/Tabs.js:5:4701)",
        "at Tab.trigger (node_modules/desktop/Events.js:79:19)",
        "at Tab.save (extensions/Tabs/Tab.js:5:553)",
        "at TabsAutosave._save (extensions/Tabs/Tabs.Autosave.js:5:1189)",
        "at Tabs.trigger (node_modules/desktop/Events.js:79:19)",
        "at Tabs.switch (extensions/Tabs/Tabs.js:5:1412)",
        "at Tabs.new (extensions/Tabs/Tabs.js:5:2125)",
        "at e.files.forEach.t (extensions/Tabs/Tabs.js:5:5560)",
        "at Array.forEach ((native)",
        "at Tabs._onProjectChange (extensions/Tabs/Tabs.js:5:5541)",
        "at Project.trigger (node_modules/desktop/Events.js:79:19)",
        "at Project.setProjectDir (extensions/Project/Project.js:5:1432)",
        "at Folders.onItemPick (extensions/Folders/Folders.js:5:627)",
        "at List.trigger (node_modules/desktop/Events.js:79:19)"
    ]
}
```

**Comment by astoilkov** [comment]
We have released a new Caret Beta update which should fix this bug.

Closing this issue. Thanks for reporting.
