### ISSUE TITLE
Got this error while opening a markdown file - Could not call remote function 

### ISSUE THREAD

**Issue by AbhishekTripathi** [careteditor/caret#877]
The following error has occurred:
```
{
    "message": "Could not call remote function ''. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from null\nError: Could not call remote function ''. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from null\n    at callFunction (D:\\dropbox\\tools\\Caret\\resources\\electron.asar\\browser\\rpc-server.js:257:11)\n    at EventEmitter.<anonymous> (D:\\dropbox\\tools\\Caret\\resources\\electron.asar\\browser\\rpc-server.js:357:5)\n    at emitMany (events.js:127:13)\n    at EventEmitter.emit (events.js:204:7)\n    at WebContents.<anonymous> (D:\\dropbox\\tools\\Caret\\resources\\electron.asar\\browser\\api\\web-contents.js:256:13)\n    at emitTwo (events.js:106:13)\n    at WebContents.emit (events.js:194:7)",
    "version": "3.4.6",
    "os": "Windows 10",
    "path": "D:\\dropbox\\tools\\Caret\\resources\\electron.asar\\renderer\\api\\remote.js",
    "code": "throw new Error(meta.message + '\\n' + meta.stack)",
    "line": 234,
    "column": 7,
    "stack": [
        "Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from null",
        "at callFunction ((D:\\dropbox\\tools\\Caret\\resources\\electron.asar\\browser\\rpc-server.js:257:11)",
        "at EventEmitter.<anonymous> ((D:\\dropbox\\tools\\Caret\\resources\\electron.asar\\browser\\rpc-server.js:357:5)",
        "at emitMany ((events.js:127:13)",
        "at EventEmitter.emit ((events.js:204:7)",
        "at WebContents.<anonymous> ((D:\\dropbox\\tools\\Caret\\resources\\electron.asar\\browser\\api\\web-contents.js:256:13)",
        "at emitTwo ((events.js:106:13)",
        "at WebContents.emit ((events.js:194:7)",
        "at metaToValue ((D:\\dropbox\\tools\\Caret\\resources\\electron.asar\\renderer\\api\\remote.js:234:13)",
        "at Object.remoteMemberFunction ((D:\\dropbox\\tools\\Caret\\resources\\electron.asar\\renderer\\api\\remote.js:118:18)",
        "at e.value ((D:\\dropbox\\tools\\Caret\\resources\\app.asar\\extensions\\Menu\\Menu.js:5:2108)",
        "at t.value ((D:\\dropbox\\tools\\Caret\\resources\\app.asar\\extensions\\TitleBar.js:5:3477)"
    ]
}
```

**Comment by astoilkov** [comment]
Thanks for reporting. We will investigate.
